# Generated by Django 3.1 on 2020-09-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=30)),
                ('tipo_palabra', models.CharField(choices=[('Sustantivo', 'Sustantivo'), ('Adjetivo', 'Adjetivo'), ('Determinante', 'Determinante'), ('Pronombre', 'Pronombre'), ('Verbo', 'Verbo'), ('Adverbio', 'Adverbio'), ('Preposiciones', 'Preposiciones'), ('Conjuncion', 'Conjuncion')], max_length=15)),
                ('definiciones', models.CharField(max_length=200)),
            ],
        ),
    ]
