# Generated by Django 3.1 on 2020-09-04 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_diccionario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Entradas',
        ),
    ]
